# Generated by Django 3.0.6 on 2020-07-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='cat_image',
        ),
    ]
