# Generated by Django 3.0.6 on 2020-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200713_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='5-6 yards', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, default='category/category_default.jpg', upload_to='category/%Y/%m/%d'),
        ),
    ]
