# Generated by Django 3.0.6 on 2020-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200726_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='category_default.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
